# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Build and Test

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: ./.github/actions/setup-pnpm
        with:
          version: 8
      - name: Run ESLint and TSC
        run: pnpm lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: ./.github/actions/setup-pnpm
        with:
          version: 8
      - name: Run tests
        run: pnpm test
