# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Lint and Test

on:
  - push
  - pull_request

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      # Set up environment
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      # Run tests
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Run ESLint and TSC
        run: pnpm lint
      - name: Run tests
        run: pnpm test
